//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Bio.Taxonomy.Data.Itis
{
    using System;
    using System.Collections.Generic;
    
    public partial class geographic_div
    {
        public int tsn { get; set; }
        public string geographic_value { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
