//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Bio.Taxonomy.Data.Itis
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxonomic_units
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public taxonomic_units()
        {
            this.reference_links = new HashSet<reference_links>();
            this.vernaculars = new HashSet<vernacular>();
        }
    
        public int tsn { get; set; }
        public string unit_ind1 { get; set; }
        public string unit_name1 { get; set; }
        public string unit_ind2 { get; set; }
        public string unit_name2 { get; set; }
        public string unit_ind3 { get; set; }
        public string unit_name3 { get; set; }
        public string unit_ind4 { get; set; }
        public string unit_name4 { get; set; }
        public string unnamed_taxon_ind { get; set; }
        public string usage { get; set; }
        public string unaccept_reason { get; set; }
        public string credibility_rtng { get; set; }
        public string completeness_rtng { get; set; }
        public string currency_rating { get; set; }
        public Nullable<short> phylo_sort_seq { get; set; }
        public System.DateTime initial_time_stamp { get; set; }
        public Nullable<int> parent_tsn { get; set; }
        public Nullable<int> taxon_author_id { get; set; }
        public Nullable<int> hybrid_author_id { get; set; }
        public short kingdom_id { get; set; }
        public short rank_id { get; set; }
        public System.DateTime update_date { get; set; }
        public string uncertain_prnt_ind { get; set; }
        public string name_usage { get; set; }
        public string complete_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reference_links> reference_links { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vernacular> vernaculars { get; set; }
    }
}
