//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Bio.Taxonomy.Data.Itis
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxon_authors_lkp
    {
        public int taxon_author_id { get; set; }
        public string taxon_author { get; set; }
        public System.DateTime update_date { get; set; }
        public short kingdom_id { get; set; }
        public string short_author { get; set; }
    }
}
