//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutActionLinkTitle {
            get {
                return ResourceManager.GetString("AboutActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string ArticlesActionLinkTitle {
            get {
                return ResourceManager.GetString("ArticlesActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string BadRequestPageHeading {
            get {
                return ResourceManager.GetString("BadRequestPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string BadRequestPageTitle {
            get {
                return ResourceManager.GetString("BadRequestPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string ContactActionLinkTitle {
            get {
                return ResourceManager.GetString("ContactActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string DeafultCreatePageHeading {
            get {
                return ResourceManager.GetString("DeafultCreatePageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string DeafultCreatePageTitle {
            get {
                return ResourceManager.GetString("DeafultCreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeafultDeletePageHeading {
            get {
                return ResourceManager.GetString("DeafultDeletePageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeafultDeletePageTitle {
            get {
                return ResourceManager.GetString("DeafultDeletePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DeafultDetailsPageHeading {
            get {
                return ResourceManager.GetString("DeafultDetailsPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DeafultDetailsPageTitle {
            get {
                return ResourceManager.GetString("DeafultDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string DeafultEditPageHeading {
            get {
                return ResourceManager.GetString("DeafultEditPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string DeafultEditPageTitle {
            get {
                return ResourceManager.GetString("DeafultEditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string DeafultIndexPageHeading {
            get {
                return ResourceManager.GetString("DeafultIndexPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string DeafultIndexPageTitle {
            get {
                return ResourceManager.GetString("DeafultIndexPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string DeafultPreviewPageHeading {
            get {
                return ResourceManager.GetString("DeafultPreviewPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string DeafultPreviewPageTitle {
            get {
                return ResourceManager.GetString("DeafultPreviewPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string DeafultUploadPageHeading {
            get {
                return ResourceManager.GetString("DeafultUploadPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string DeafultUploadPageTitle {
            get {
                return ResourceManager.GetString("DeafultUploadPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string DefaultBackToListActionLinkTitle {
            get {
                return ResourceManager.GetString("DefaultBackToListActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string DefaultCreateActionLinkTitle {
            get {
                return ResourceManager.GetString("DefaultCreateActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DefaultDeleteActionLinkTitle {
            get {
                return ResourceManager.GetString("DefaultDeleteActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DefaultDetailsActionLinkTitle {
            get {
                return ResourceManager.GetString("DefaultDetailsActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string DefaultDownloadActionLinkTitle {
            get {
                return ResourceManager.GetString("DefaultDownloadActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string DefaultEditActionLinkTitle {
            get {
                return ResourceManager.GetString("DefaultEditActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string DefaultIndexActionLinkTitle {
            get {
                return ResourceManager.GetString("DefaultIndexActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string DefaultPreviewActionLinkTitle {
            get {
                return ResourceManager.GetString("DefaultPreviewActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string DefaultRefreshActionLinkTitle {
            get {
                return ResourceManager.GetString("DefaultRefreshActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string DefaultSaveActionLinkTitle {
            get {
                return ResourceManager.GetString("DefaultSaveActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload New File or Files.
        /// </summary>
        internal static string DefaultUploadNewFileActionLinkTitle {
            get {
                return ResourceManager.GetString("DefaultUploadNewFileActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document saved successfully.
        /// </summary>
        internal static string DocumentSavedSuccessfullyResponseMessage {
            get {
                return ResourceManager.GetString("DocumentSavedSuccessfullyResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request.
        /// </summary>
        internal static string ErrorPageHeading {
            get {
                return ResourceManager.GetString("ErrorPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorPageTitle {
            get {
                return ResourceManager.GetString("ErrorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string FilesActionLinkTitle {
            get {
                return ResourceManager.GetString("FilesActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, go back and try again..
        /// </summary>
        internal static string GoBackAndTryAgainMessage {
            get {
                return ResourceManager.GetString("GoBackAndTryAgainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpActionLinkTitle {
            get {
                return ResourceManager.GetString("HelpActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpMenuItemTitle {
            get {
                return ResourceManager.GetString("HelpMenuItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpPageHeading {
            get {
                return ResourceManager.GetString("HelpPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpPageTitle {
            get {
                return ResourceManager.GetString("HelpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpSubmenuTitle {
            get {
                return ResourceManager.GetString("HelpSubmenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeActionLinkTitle {
            get {
                return ResourceManager.GetString("HomeActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Action.
        /// </summary>
        internal static string InvalidActionPageHeading {
            get {
                return ResourceManager.GetString("InvalidActionPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Action.
        /// </summary>
        internal static string InvalidActionPageTitle {
            get {
                return ResourceManager.GetString("InvalidActionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid ID is expected.
        /// </summary>
        internal static string InvalidIdPageHeading {
            get {
                return ResourceManager.GetString("InvalidIdPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID.
        /// </summary>
        internal static string InvalidIdPageTitle {
            get {
                return ResourceManager.GetString("InvalidIdPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Or Empty File or Files.
        /// </summary>
        internal static string InvalidOrEmptyFilePageHeading {
            get {
                return ResourceManager.GetString("InvalidOrEmptyFilePageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Or Empty File.
        /// </summary>
        internal static string InvalidOrEmptyFilePageTitle {
            get {
                return ResourceManager.GetString("InvalidOrEmptyFilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Page Number.
        /// </summary>
        internal static string InvalidPageNumberPageHeading {
            get {
                return ResourceManager.GetString("InvalidPageNumberPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Page Number.
        /// </summary>
        internal static string InvalidPageNumberPageTitle {
            get {
                return ResourceManager.GetString("InvalidPageNumberPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid User ID is expected.
        /// </summary>
        internal static string InvalidUserIdPageHeading {
            get {
                return ResourceManager.GetString("InvalidUserIdPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User ID.
        /// </summary>
        internal static string InvalidUserIdPageTitle {
            get {
                return ResourceManager.GetString("InvalidUserIdPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journals.
        /// </summary>
        internal static string JournalActionLinkTitle {
            get {
                return ResourceManager.GetString("JournalActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Files.
        /// </summary>
        internal static string ListOfFilesPageHeading {
            get {
                return ResourceManager.GetString("ListOfFilesPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Files.
        /// </summary>
        internal static string ListOfFilesPageTitle {
            get {
                return ResourceManager.GetString("ListOfFilesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LoginActionLinkTitle {
            get {
                return ResourceManager.GetString("LoginActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        internal static string LogoutActionLinkTitle {
            get {
                return ResourceManager.GetString("LogoutActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Files Selected.
        /// </summary>
        internal static string NoFilesSelectedPageHeading {
            get {
                return ResourceManager.GetString("NoFilesSelectedPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Files Selected.
        /// </summary>
        internal static string NoFilesSelectedPageTitle {
            get {
                return ResourceManager.GetString("NoFilesSelectedPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string NotFoundPageHeading {
            get {
                return ResourceManager.GetString("NotFoundPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string NotFoundPageTitle {
            get {
                return ResourceManager.GetString("NotFoundPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers.
        /// </summary>
        internal static string PublishersActionLinkTitle {
            get {
                return ResourceManager.GetString("PublishersActionLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterActionLinkTitle {
            get {
                return ResourceManager.GetString("RegisterActionLinkTitle", resourceCulture);
            }
        }
    }
}
