//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Bio.Taxonomy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class publication
    {
        public string pub_id_prefix { get; set; }
        public int publication_id { get; set; }
        public string reference_author { get; set; }
        public string title { get; set; }
        public string publication_name { get; set; }
        public Nullable<System.DateTime> listed_pub_date { get; set; }
        public Nullable<System.DateTime> actual_pub_date { get; set; }
        public string publisher { get; set; }
        public string pub_place { get; set; }
        public string isbn { get; set; }
        public string issn { get; set; }
        public string pages { get; set; }
        public string pub_comment { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
