//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Bio.Taxonomy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vern_ref_links
    {
        public int tsn { get; set; }
        public string doc_id_prefix { get; set; }
        public int documentation_id { get; set; }
        public System.DateTime update_date { get; set; }
        public int vern_id { get; set; }
    
        public virtual vernacular vernacular { get; set; }
    }
}
