//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.MainProgram {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessingTools.MainProgram.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Clone ZooBank json.
        ///.
        /// </summary>
        internal static string CloneZooBankJsonMessage {
            get {
                return ResourceManager.GetString("CloneZooBankJsonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Clone ZooBank xml.
        ///.
        /// </summary>
        internal static string CloneZooBankXmlMessage {
            get {
                return ResourceManager.GetString("CloneZooBankXmlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time {0}..
        /// </summary>
        internal static string ElapsedTimeMessageFormat {
            get {
                return ResourceManager.GetString("ElapsedTimeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Expand taxa.
        ///.
        /// </summary>
        internal static string ExpandTaxa {
            get {
                return ResourceManager.GetString("ExpandTaxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Extract all taxa.
        ///.
        /// </summary>
        internal static string ExtractAllTaxaMessage {
            get {
                return ResourceManager.GetString("ExtractAllTaxaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Extract higher taxa.
        ///.
        /// </summary>
        internal static string ExtractHigherTaxaMessage {
            get {
                return ResourceManager.GetString("ExtractHigherTaxaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        Extract lower taxa.
        ///.
        /// </summary>
        internal static string ExtractLowerTaxaMessage {
            get {
                return ResourceManager.GetString("ExtractLowerTaxaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Format treatments.
        ///.
        /// </summary>
        internal static string FormatTreatmentsMessage {
            get {
                return ResourceManager.GetString("FormatTreatmentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Generate xml document for registration in ZooBank.
        ///.
        /// </summary>
        internal static string GenerateRegistrationXmlForZooBankMessage {
            get {
                return ResourceManager.GetString("GenerateRegistrationXmlForZooBankMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: Tagger -&lt;options&gt; &lt;input file name&gt;[ &lt;output file name&gt;[ &lt;query|zoobank input file&gt;]][ --&lt;double-dashed options&gt;]
        ///where:
        ///Options:
        ///    h, ? = print this message and exit
        ///
        ///    --system = use System-style processing
        ///    --nlm = use NLM-style processing
        ///    i = perform initial format
        ///    w = tag web links
        ///    d = tag DOI
        ///    f = tag figures and tables
        ///    m = resolve mediatypes
        ///    --table-fn = tag table foot notes
        ///
        ///    c = tag coordinates
        ///    k = parse coordinates
        ///
        ///    r = Parse referen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Initial format.
        ///.
        /// </summary>
        internal static string InitialFormatMessage {
            get {
                return ResourceManager.GetString("InitialFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file name: {0}
        ///Output file name: {1}
        ///{2}.
        /// </summary>
        internal static string InputOutputFileNamesMessageFormat {
            get {
                return ResourceManager.GetString("InputOutputFileNamesMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Parse coordinates.
        ///.
        /// </summary>
        internal static string ParseCoordinatesMessage {
            get {
                return ResourceManager.GetString("ParseCoordinatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Make higher taxa of type &apos;above-genus&apos;.
        ///.
        /// </summary>
        internal static string ParseHigherTaxaAboveGenusMessage {
            get {
                return ResourceManager.GetString("ParseHigherTaxaAboveGenusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Parse higher taxa by suffix.
        ///.
        /// </summary>
        internal static string ParseHigherTaxaBySuffixMessage {
            get {
                return ResourceManager.GetString("ParseHigherTaxaBySuffixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Parse higher taxa.
        ///.
        /// </summary>
        internal static string ParseHigherTaxaMessage {
            get {
                return ResourceManager.GetString("ParseHigherTaxaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Parse higher taxa using Aphia.
        ///.
        /// </summary>
        internal static string ParseHigherTaxaWithAphiaMessage {
            get {
                return ResourceManager.GetString("ParseHigherTaxaWithAphiaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Parse higher taxa using CoL.
        ///.
        /// </summary>
        internal static string ParseHigherTaxaWithCoLMessage {
            get {
                return ResourceManager.GetString("ParseHigherTaxaWithCoLMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Parse higher taxa using GBIF.
        ///.
        /// </summary>
        internal static string ParseHigherTaxaWithGbifMessage {
            get {
                return ResourceManager.GetString("ParseHigherTaxaWithGbifMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Parse lower taxa.
        ///.
        /// </summary>
        internal static string ParseLowerTaxaMessage {
            get {
                return ResourceManager.GetString("ParseLowerTaxaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Parse references.
        ///.
        /// </summary>
        internal static string ParseReferencesMessage {
            get {
                return ResourceManager.GetString("ParseReferencesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Parse treatment meta with Aphia.
        ///.
        /// </summary>
        internal static string ParseTreatmentMetaWithAphiaMessage {
            get {
                return ResourceManager.GetString("ParseTreatmentMetaWithAphiaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Parse treatment meta with CoL.
        ///.
        /// </summary>
        internal static string ParseTreatmentMetaWithCoLMessage {
            get {
                return ResourceManager.GetString("ParseTreatmentMetaWithCoLMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Parse treatment meta with GBIF.
        ///.
        /// </summary>
        internal static string ParseTreatmentMetaWithGbifMessage {
            get {
                return ResourceManager.GetString("ParseTreatmentMetaWithGbifMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Resolve mediatypes.
        ///.
        /// </summary>
        internal static string ResolveMediaTypesMessage {
            get {
                return ResourceManager.GetString("ResolveMediaTypesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Custom XSL transform.
        ///.
        /// </summary>
        internal static string RunCustomXslTransformMessage {
            get {
                return ResourceManager.GetString("RunCustomXslTransformMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Tag abbreviations.
        ///.
        /// </summary>
        internal static string TagAbbreviationsMessage {
            get {
                return ResourceManager.GetString("TagAbbreviationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Tag codes.
        ///.
        /// </summary>
        internal static string TagCodesMessage {
            get {
                return ResourceManager.GetString("TagCodesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Tag coordinates.
        ///.
        /// </summary>
        internal static string TagCoordinatesMessage {
            get {
                return ResourceManager.GetString("TagCoordinatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Tag dates.
        ///.
        /// </summary>
        internal static string TagDatesMessage {
            get {
                return ResourceManager.GetString("TagDatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Tag DOI.
        ///.
        /// </summary>
        internal static string TagDoiMessage {
            get {
                return ResourceManager.GetString("TagDoiMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Tag envo terms using EXTRACT.
        ///.
        /// </summary>
        internal static string TagEnvironmentsMessage {
            get {
                return ResourceManager.GetString("TagEnvironmentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Tag envo terms using local database.
        ///.
        /// </summary>
        internal static string TagEnvoTermsMessage {
            get {
                return ResourceManager.GetString("TagEnvoTermsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Tag floats.
        ///.
        /// </summary>
        internal static string TagFloatsMessage {
            get {
                return ResourceManager.GetString("TagFloatsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Tag higher taxa.
        ///.
        /// </summary>
        internal static string TagHigherTaxaMessage {
            get {
                return ResourceManager.GetString("TagHigherTaxaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Tag lower taxa.
        ///.
        /// </summary>
        internal static string TagLowerTaxaMessage {
            get {
                return ResourceManager.GetString("TagLowerTaxaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Tag quantities.
        ///.
        /// </summary>
        internal static string TagQuantitiesMessage {
            get {
                return ResourceManager.GetString("TagQuantitiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Tag references.
        ///.
        /// </summary>
        internal static string TagReferencesMessage {
            get {
                return ResourceManager.GetString("TagReferencesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Tag table foot-notes.
        ///.
        /// </summary>
        internal static string TagTableFootNotesMessage {
            get {
                return ResourceManager.GetString("TagTableFootNotesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Tag web links.
        ///.
        /// </summary>
        internal static string TagWebLinksMessage {
            get {
                return ResourceManager.GetString("TagWebLinksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Taxa validation using Global names resolver.
        ///.
        /// </summary>
        internal static string ValidateTaxaUsingGnrMessage {
            get {
                return ResourceManager.GetString("ValidateTaxaUsingGnrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    Writing data to output file.
        ///.
        /// </summary>
        internal static string WriteOutputFileMessage {
            get {
                return ResourceManager.GetString("WriteOutputFileMessage", resourceCulture);
            }
        }
    }
}
