//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Bio.Biorepositories.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biorepository
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public string NameOfInstitution { get; set; }
        public Nullable<bool> IsIndexHerbariorumRecord { get; set; }
        public string InstitutionalCode { get; set; }
        public string AdditionalInstitutionNames { get; set; }
        public string UrlForMainInstitutionalWebsite { get; set; }
        public string UrlForInstitutionalSpecimenCatalog { get; set; }
        public string UrlForInstitutionalWebservices { get; set; }
        public Nullable<bool> IsActiveStatusOfInstitution { get; set; }
        public string InstitutionalGovernance { get; set; }
        public string InstitutionType { get; set; }
        public string Country { get; set; }
    }
}
