//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingToolsMessaging.Messages
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessingToolsMessaging.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagging coordinates.
        /// </summary>
        internal static string coordinatesMessage {
            get {
                return ResourceManager.GetString("coordinatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagging DOI numbers.
        /// </summary>
        internal static string doiMessage {
            get {
                return ResourceManager.GetString("doiMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final format.
        /// </summary>
        internal static string finalFormatMessage {
            get {
                return ResourceManager.GetString("finalFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagging figures and tables.
        /// </summary>
        internal static string floatsMessage {
            get {
                return ResourceManager.GetString("floatsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: Tagger -&lt;options&gt; &lt;input file name&gt;[ &lt;output file name&gt;[ &lt;query|zoobank input file&gt;]][ --&lt;double-dashed options&gt;]
        ///where:
        ///Options:
        ///    h, ? = print this message and exit
        ///
        ///    --system = use System-style processing
        ///    --nlm = use NLM-style processing
        ///    i = perform initial format
        ///    w = tag web links
        ///    d = tag DOI
        ///    f = tag figures and tables
        ///    --table-fn = tag table foot notes
        ///
        ///    c = tag coordinates
        ///    k = parse coordinates
        ///
        ///    r = Parse references [under construction]
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helpMessage {
            get {
                return ResourceManager.GetString("helpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formating HTML file.
        /// </summary>
        internal static string htmlProcessMessage {
            get {
                return ResourceManager.GetString("htmlProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial format.
        /// </summary>
        internal static string initialFormatMessage {
            get {
                return ResourceManager.GetString("initialFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formating NLM XML file.
        /// </summary>
        internal static string nlmProcessMessage {
            get {
                return ResourceManager.GetString("nlmProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing references.
        /// </summary>
        internal static string parseReferencesMessage {
            get {
                return ResourceManager.GetString("parseReferencesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Institutional codes.
        /// </summary>
        internal static string tagInstitutionalCodes {
            get {
                return ResourceManager.GetString("tagInstitutionalCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanding shortened genera with StableExpand[ and UnstableExpand 1, 2, 3]:.
        /// </summary>
        internal static string taxaExpandMessage {
            get {
                return ResourceManager.GetString("taxaExpandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting treatements and tagging taxons.
        /// </summary>
        internal static string taxonomyMessage {
            get {
                return ResourceManager.GetString("taxonomyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagging web links.
        /// </summary>
        internal static string webLinksMessage {
            get {
                return ResourceManager.GetString("webLinksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing data to output file.
        /// </summary>
        internal static string writeOutputFileMessage {
            get {
                return ResourceManager.GetString("writeOutputFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoobank cloner.
        /// </summary>
        internal static string zoobankCloneMessage {
            get {
                return ResourceManager.GetString("zoobankCloneMessage", resourceCulture);
            }
        }
    }
}
