//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Clients.ConnectedServices.Bio.Aphia
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aphia/v1.0", ConfigurationName="ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaNameServicePortType")]
    public interface AphiaNameServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaIDResponse> getAphiaIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaRecords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsResponse> getAphiaRecordsAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaNameByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaNameByIDResponse> getAphiaNameByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaNameByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaRecordByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordByIDResponse> getAphiaRecordByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaRecordByExtID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordByExtIDResponse> getAphiaRecordByExtIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordByExtIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getExtIDbyAphiaID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getExtIDbyAphiaIDResponse> getExtIDbyAphiaIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getExtIDbyAphiaIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaRecordsByNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsByNamesResponse> getAphiaRecordsByNamesAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsByNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaRecordsByVernacular", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsByVernacularResponse> getAphiaRecordsByVernacularAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsByVernacularRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaRecordsByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsByDateResponse> getAphiaRecordsByDateAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsByDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaClassificationByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaClassificationByIDResponse> getAphiaClassificationByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaClassificationByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getSourcesByAphiaID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getSourcesByAphiaIDResponse> getSourcesByAphiaIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getSourcesByAphiaIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaSynonymsByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaSynonymsByIDResponse> getAphiaSynonymsByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaSynonymsByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaVernacularsByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaVernacularsByIDResponse> getAphiaVernacularsByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaVernacularsByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaChildrenByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaChildrenByIDResponse> getAphiaChildrenByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaChildrenByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="matchAphiaRecordsByNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.matchAphiaRecordsByNamesResponse> matchAphiaRecordsByNamesAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.matchAphiaRecordsByNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaDistributionsByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaDistributionsByIDResponse> getAphiaDistributionsByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaDistributionsByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaAttributeKeysByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaAttributeKeysByIDResponse> getAphiaAttributeKeysByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaAttributeKeysByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaAttributeValuesByCategoryID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaAttributeValuesByCategoryIDResponse> getAphiaAttributeValuesByCategoryIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaAttributeValuesByCategoryIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaIDsByAttributeKeyID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaIDsByAttributeKeyIDResponse> getAphiaIDsByAttributeKeyIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaIDsByAttributeKeyIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getAphiaAttributesByAphiaID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Attribute))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributeKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Distribution))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vernacular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Source))]
        System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaAttributesByAphiaIDResponse> getAphiaAttributesByAphiaIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaAttributesByAphiaIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaID", WrapperNamespace="http://aphia/v1.0/AphiaID", IsWrapped=true)]
    public partial class getAphiaIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string scientificname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public bool marine_only;
        
        public getAphiaIDRequest()
        {
        }
        
        public getAphiaIDRequest(string scientificname, bool marine_only)
        {
            this.scientificname = scientificname;
            this.marine_only = marine_only;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaIDResponse", WrapperNamespace="http://aphia/v1.0/AphiaID", IsWrapped=true)]
    public partial class getAphiaIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public getAphiaIDResponse()
        {
        }
        
        public getAphiaIDResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://aphia/v1.0")]
    public partial class AphiaRecord
    {
        
        private int aphiaIDField;
        
        private string urlField;
        
        private string scientificnameField;
        
        private string authorityField;
        
        private string rankField;
        
        private string statusField;
        
        private string unacceptreasonField;
        
        private int valid_AphiaIDField;
        
        private string valid_nameField;
        
        private string valid_authorityField;
        
        private string kingdomField;
        
        private string phylumField;
        
        private string classField;
        
        private string orderField;
        
        private string familyField;
        
        private string genusField;
        
        private string citationField;
        
        private string lsidField;
        
        private int isMarineField;
        
        private int isBrackishField;
        
        private int isFreshwaterField;
        
        private int isTerrestrialField;
        
        private int isExtinctField;
        
        private string match_typeField;
        
        private string modifiedField;
        
        /// <remarks/>
        public int AphiaID
        {
            get
            {
                return this.aphiaIDField;
            }
            set
            {
                this.aphiaIDField = value;
            }
        }
        
        /// <remarks/>
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string scientificname
        {
            get
            {
                return this.scientificnameField;
            }
            set
            {
                this.scientificnameField = value;
            }
        }
        
        /// <remarks/>
        public string authority
        {
            get
            {
                return this.authorityField;
            }
            set
            {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public string rank
        {
            get
            {
                return this.rankField;
            }
            set
            {
                this.rankField = value;
            }
        }
        
        /// <remarks/>
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string unacceptreason
        {
            get
            {
                return this.unacceptreasonField;
            }
            set
            {
                this.unacceptreasonField = value;
            }
        }
        
        /// <remarks/>
        public int valid_AphiaID
        {
            get
            {
                return this.valid_AphiaIDField;
            }
            set
            {
                this.valid_AphiaIDField = value;
            }
        }
        
        /// <remarks/>
        public string valid_name
        {
            get
            {
                return this.valid_nameField;
            }
            set
            {
                this.valid_nameField = value;
            }
        }
        
        /// <remarks/>
        public string valid_authority
        {
            get
            {
                return this.valid_authorityField;
            }
            set
            {
                this.valid_authorityField = value;
            }
        }
        
        /// <remarks/>
        public string kingdom
        {
            get
            {
                return this.kingdomField;
            }
            set
            {
                this.kingdomField = value;
            }
        }
        
        /// <remarks/>
        public string phylum
        {
            get
            {
                return this.phylumField;
            }
            set
            {
                this.phylumField = value;
            }
        }
        
        /// <remarks/>
        public string @class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        public string order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public string family
        {
            get
            {
                return this.familyField;
            }
            set
            {
                this.familyField = value;
            }
        }
        
        /// <remarks/>
        public string genus
        {
            get
            {
                return this.genusField;
            }
            set
            {
                this.genusField = value;
            }
        }
        
        /// <remarks/>
        public string citation
        {
            get
            {
                return this.citationField;
            }
            set
            {
                this.citationField = value;
            }
        }
        
        /// <remarks/>
        public string lsid
        {
            get
            {
                return this.lsidField;
            }
            set
            {
                this.lsidField = value;
            }
        }
        
        /// <remarks/>
        public int isMarine
        {
            get
            {
                return this.isMarineField;
            }
            set
            {
                this.isMarineField = value;
            }
        }
        
        /// <remarks/>
        public int isBrackish
        {
            get
            {
                return this.isBrackishField;
            }
            set
            {
                this.isBrackishField = value;
            }
        }
        
        /// <remarks/>
        public int isFreshwater
        {
            get
            {
                return this.isFreshwaterField;
            }
            set
            {
                this.isFreshwaterField = value;
            }
        }
        
        /// <remarks/>
        public int isTerrestrial
        {
            get
            {
                return this.isTerrestrialField;
            }
            set
            {
                this.isTerrestrialField = value;
            }
        }
        
        /// <remarks/>
        public int isExtinct
        {
            get
            {
                return this.isExtinctField;
            }
            set
            {
                this.isExtinctField = value;
            }
        }
        
        /// <remarks/>
        public string match_type
        {
            get
            {
                return this.match_typeField;
            }
            set
            {
                this.match_typeField = value;
            }
        }
        
        /// <remarks/>
        public string modified
        {
            get
            {
                return this.modifiedField;
            }
            set
            {
                this.modifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://aphia/v1.0")]
    public partial class Attribute
    {
        
        private int aphiaIDField;
        
        private int measurementTypeIDField;
        
        private string measurementTypeField;
        
        private string measurementValueField;
        
        private int source_idField;
        
        private string referenceField;
        
        private string qualitystatusField;
        
        private int categoryIDField;
        
        private int aphiaID_InheritedField;
        
        private Attribute[] childrenField;
        
        /// <remarks/>
        public int AphiaID
        {
            get
            {
                return this.aphiaIDField;
            }
            set
            {
                this.aphiaIDField = value;
            }
        }
        
        /// <remarks/>
        public int measurementTypeID
        {
            get
            {
                return this.measurementTypeIDField;
            }
            set
            {
                this.measurementTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string measurementType
        {
            get
            {
                return this.measurementTypeField;
            }
            set
            {
                this.measurementTypeField = value;
            }
        }
        
        /// <remarks/>
        public string measurementValue
        {
            get
            {
                return this.measurementValueField;
            }
            set
            {
                this.measurementValueField = value;
            }
        }
        
        /// <remarks/>
        public int source_id
        {
            get
            {
                return this.source_idField;
            }
            set
            {
                this.source_idField = value;
            }
        }
        
        /// <remarks/>
        public string reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string qualitystatus
        {
            get
            {
                return this.qualitystatusField;
            }
            set
            {
                this.qualitystatusField = value;
            }
        }
        
        /// <remarks/>
        public int CategoryID
        {
            get
            {
                return this.categoryIDField;
            }
            set
            {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        public int AphiaID_Inherited
        {
            get
            {
                return this.aphiaID_InheritedField;
            }
            set
            {
                this.aphiaID_InheritedField = value;
            }
        }
        
        /// <remarks/>
        public Attribute[] children
        {
            get
            {
                return this.childrenField;
            }
            set
            {
                this.childrenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://aphia/v1.0")]
    public partial class AttributeValue
    {
        
        private int measurementValueIDField;
        
        private string measurementValueField;
        
        private string measurementValueCodeField;
        
        private AttributeValue[] childrenField;
        
        /// <remarks/>
        public int measurementValueID
        {
            get
            {
                return this.measurementValueIDField;
            }
            set
            {
                this.measurementValueIDField = value;
            }
        }
        
        /// <remarks/>
        public string measurementValue
        {
            get
            {
                return this.measurementValueField;
            }
            set
            {
                this.measurementValueField = value;
            }
        }
        
        /// <remarks/>
        public string measurementValueCode
        {
            get
            {
                return this.measurementValueCodeField;
            }
            set
            {
                this.measurementValueCodeField = value;
            }
        }
        
        /// <remarks/>
        public AttributeValue[] children
        {
            get
            {
                return this.childrenField;
            }
            set
            {
                this.childrenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://aphia/v1.0")]
    public partial class AttributeKey
    {
        
        private int measurementTypeIDField;
        
        private string measurementTypeField;
        
        private int input_idField;
        
        private int categoryIDField;
        
        private AttributeKey[] childrenField;
        
        /// <remarks/>
        public int measurementTypeID
        {
            get
            {
                return this.measurementTypeIDField;
            }
            set
            {
                this.measurementTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string measurementType
        {
            get
            {
                return this.measurementTypeField;
            }
            set
            {
                this.measurementTypeField = value;
            }
        }
        
        /// <remarks/>
        public int input_id
        {
            get
            {
                return this.input_idField;
            }
            set
            {
                this.input_idField = value;
            }
        }
        
        /// <remarks/>
        public int CategoryID
        {
            get
            {
                return this.categoryIDField;
            }
            set
            {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        public AttributeKey[] children
        {
            get
            {
                return this.childrenField;
            }
            set
            {
                this.childrenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://aphia/v1.0")]
    public partial class Distribution
    {
        
        private string localityField;
        
        private string locationIDField;
        
        private string higherGeographyField;
        
        private string higherGeographyIDField;
        
        private string recordStatusField;
        
        private string typeStatusField;
        
        private string establishmentMeansField;
        
        private float decimalLatitudeField;
        
        private float decimalLongitudeField;
        
        private string qualityStatusField;
        
        /// <remarks/>
        public string locality
        {
            get
            {
                return this.localityField;
            }
            set
            {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        public string locationID
        {
            get
            {
                return this.locationIDField;
            }
            set
            {
                this.locationIDField = value;
            }
        }
        
        /// <remarks/>
        public string higherGeography
        {
            get
            {
                return this.higherGeographyField;
            }
            set
            {
                this.higherGeographyField = value;
            }
        }
        
        /// <remarks/>
        public string higherGeographyID
        {
            get
            {
                return this.higherGeographyIDField;
            }
            set
            {
                this.higherGeographyIDField = value;
            }
        }
        
        /// <remarks/>
        public string recordStatus
        {
            get
            {
                return this.recordStatusField;
            }
            set
            {
                this.recordStatusField = value;
            }
        }
        
        /// <remarks/>
        public string typeStatus
        {
            get
            {
                return this.typeStatusField;
            }
            set
            {
                this.typeStatusField = value;
            }
        }
        
        /// <remarks/>
        public string establishmentMeans
        {
            get
            {
                return this.establishmentMeansField;
            }
            set
            {
                this.establishmentMeansField = value;
            }
        }
        
        /// <remarks/>
        public float decimalLatitude
        {
            get
            {
                return this.decimalLatitudeField;
            }
            set
            {
                this.decimalLatitudeField = value;
            }
        }
        
        /// <remarks/>
        public float decimalLongitude
        {
            get
            {
                return this.decimalLongitudeField;
            }
            set
            {
                this.decimalLongitudeField = value;
            }
        }
        
        /// <remarks/>
        public string qualityStatus
        {
            get
            {
                return this.qualityStatusField;
            }
            set
            {
                this.qualityStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://aphia/v1.0")]
    public partial class Vernacular
    {
        
        private string vernacularField;
        
        private string language_codeField;
        
        private string languageField;
        
        /// <remarks/>
        public string vernacular
        {
            get
            {
                return this.vernacularField;
            }
            set
            {
                this.vernacularField = value;
            }
        }
        
        /// <remarks/>
        public string language_code
        {
            get
            {
                return this.language_codeField;
            }
            set
            {
                this.language_codeField = value;
            }
        }
        
        /// <remarks/>
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://aphia/v1.0")]
    public partial class Source
    {
        
        private int source_idField;
        
        private string useField;
        
        private string referenceField;
        
        private string pageField;
        
        private string urlField;
        
        private string linkField;
        
        private string fulltextField;
        
        private string doiField;
        
        /// <remarks/>
        public int source_id
        {
            get
            {
                return this.source_idField;
            }
            set
            {
                this.source_idField = value;
            }
        }
        
        /// <remarks/>
        public string use
        {
            get
            {
                return this.useField;
            }
            set
            {
                this.useField = value;
            }
        }
        
        /// <remarks/>
        public string reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public string fulltext
        {
            get
            {
                return this.fulltextField;
            }
            set
            {
                this.fulltextField = value;
            }
        }
        
        /// <remarks/>
        public string doi
        {
            get
            {
                return this.doiField;
            }
            set
            {
                this.doiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://aphia/v1.0")]
    public partial class Classification
    {
        
        private int aphiaIDField;
        
        private string rankField;
        
        private string scientificnameField;
        
        private Classification childField;
        
        /// <remarks/>
        public int AphiaID
        {
            get
            {
                return this.aphiaIDField;
            }
            set
            {
                this.aphiaIDField = value;
            }
        }
        
        /// <remarks/>
        public string rank
        {
            get
            {
                return this.rankField;
            }
            set
            {
                this.rankField = value;
            }
        }
        
        /// <remarks/>
        public string scientificname
        {
            get
            {
                return this.scientificnameField;
            }
            set
            {
                this.scientificnameField = value;
            }
        }
        
        /// <remarks/>
        public Classification child
        {
            get
            {
                return this.childField;
            }
            set
            {
                this.childField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecords", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaRecordsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string scientificname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public bool like;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public bool fuzzy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public bool marine_only;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int offset;
        
        public getAphiaRecordsRequest()
        {
        }
        
        public getAphiaRecordsRequest(string scientificname, bool like, bool fuzzy, bool marine_only, int offset)
        {
            this.scientificname = scientificname;
            this.like = like;
            this.fuzzy = fuzzy;
            this.marine_only = marine_only;
            this.offset = offset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordsResponse", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaRecordsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord[] @return;
        
        public getAphiaRecordsResponse()
        {
        }
        
        public getAphiaRecordsResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaNameByID", WrapperNamespace="http://aphia/v1.0/AphiaName", IsWrapped=true)]
    public partial class getAphiaNameByIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        public getAphiaNameByIDRequest()
        {
        }
        
        public getAphiaNameByIDRequest(int AphiaID)
        {
            this.AphiaID = AphiaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaNameByIDResponse", WrapperNamespace="http://aphia/v1.0/AphiaName", IsWrapped=true)]
    public partial class getAphiaNameByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public getAphiaNameByIDResponse()
        {
        }
        
        public getAphiaNameByIDResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordByID", WrapperNamespace="http://aphia/v1.0/AphiaRecord", IsWrapped=true)]
    public partial class getAphiaRecordByIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        public getAphiaRecordByIDRequest()
        {
        }
        
        public getAphiaRecordByIDRequest(int AphiaID)
        {
            this.AphiaID = AphiaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordByIDResponse", WrapperNamespace="http://aphia/v1.0/AphiaRecord", IsWrapped=true)]
    public partial class getAphiaRecordByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord @return;
        
        public getAphiaRecordByIDResponse()
        {
        }
        
        public getAphiaRecordByIDResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordByExtID", WrapperNamespace="http://aphia/v1.0/AphiaRecord", IsWrapped=true)]
    public partial class getAphiaRecordByExtIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string type;
        
        public getAphiaRecordByExtIDRequest()
        {
        }
        
        public getAphiaRecordByExtIDRequest(string id, string type)
        {
            this.id = id;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordByExtIDResponse", WrapperNamespace="http://aphia/v1.0/AphiaRecord", IsWrapped=true)]
    public partial class getAphiaRecordByExtIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord @return;
        
        public getAphiaRecordByExtIDResponse()
        {
        }
        
        public getAphiaRecordByExtIDResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getExtIDbyAphiaID", WrapperNamespace="http://aphia/v1.0/externalidentifiers", IsWrapped=true)]
    public partial class getExtIDbyAphiaIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string type;
        
        public getExtIDbyAphiaIDRequest()
        {
        }
        
        public getExtIDbyAphiaIDRequest(int AphiaID, string type)
        {
            this.AphiaID = AphiaID;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getExtIDbyAphiaIDResponse", WrapperNamespace="http://aphia/v1.0/externalidentifiers", IsWrapped=true)]
    public partial class getExtIDbyAphiaIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] @return;
        
        public getExtIDbyAphiaIDResponse()
        {
        }
        
        public getExtIDbyAphiaIDResponse(string[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordsByNames", WrapperNamespace="http://aphia/v1.0/AphiaMatches", IsWrapped=true)]
    public partial class getAphiaRecordsByNamesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] scientificnames;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public bool like;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public bool fuzzy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public bool marine_only;
        
        public getAphiaRecordsByNamesRequest()
        {
        }
        
        public getAphiaRecordsByNamesRequest(string[] scientificnames, bool like, bool fuzzy, bool marine_only)
        {
            this.scientificnames = scientificnames;
            this.like = like;
            this.fuzzy = fuzzy;
            this.marine_only = marine_only;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordsByNamesResponse", WrapperNamespace="http://aphia/v1.0/AphiaMatches", IsWrapped=true)]
    public partial class getAphiaRecordsByNamesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord[][] @return;
        
        public getAphiaRecordsByNamesResponse()
        {
        }
        
        public getAphiaRecordsByNamesResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord[][] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordsByVernacular", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaRecordsByVernacularRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string vernacular;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public bool like;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int offset;
        
        public getAphiaRecordsByVernacularRequest()
        {
        }
        
        public getAphiaRecordsByVernacularRequest(string vernacular, bool like, int offset)
        {
            this.vernacular = vernacular;
            this.like = like;
            this.offset = offset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordsByVernacularResponse", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaRecordsByVernacularResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord[] @return;
        
        public getAphiaRecordsByVernacularResponse()
        {
        }
        
        public getAphiaRecordsByVernacularResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordsByDate", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaRecordsByDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string enddate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public bool marine_only;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int offset;
        
        public getAphiaRecordsByDateRequest()
        {
        }
        
        public getAphiaRecordsByDateRequest(string startdate, string enddate, bool marine_only, int offset)
        {
            this.startdate = startdate;
            this.enddate = enddate;
            this.marine_only = marine_only;
            this.offset = offset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaRecordsByDateResponse", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaRecordsByDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord[] @return;
        
        public getAphiaRecordsByDateResponse()
        {
        }
        
        public getAphiaRecordsByDateResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaClassificationByID", WrapperNamespace="http://aphia/v1.0/Classification", IsWrapped=true)]
    public partial class getAphiaClassificationByIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        public getAphiaClassificationByIDRequest()
        {
        }
        
        public getAphiaClassificationByIDRequest(int AphiaID)
        {
            this.AphiaID = AphiaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaClassificationByIDResponse", WrapperNamespace="http://aphia/v1.0/Classification", IsWrapped=true)]
    public partial class getAphiaClassificationByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.Classification @return;
        
        public getAphiaClassificationByIDResponse()
        {
        }
        
        public getAphiaClassificationByIDResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.Classification @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSourcesByAphiaID", WrapperNamespace="http://aphia/v1.0/Sources", IsWrapped=true)]
    public partial class getSourcesByAphiaIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        public getSourcesByAphiaIDRequest()
        {
        }
        
        public getSourcesByAphiaIDRequest(int AphiaID)
        {
            this.AphiaID = AphiaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSourcesByAphiaIDResponse", WrapperNamespace="http://aphia/v1.0/Sources", IsWrapped=true)]
    public partial class getSourcesByAphiaIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.Source[] @return;
        
        public getSourcesByAphiaIDResponse()
        {
        }
        
        public getSourcesByAphiaIDResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.Source[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaSynonymsByID", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaSynonymsByIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        public getAphiaSynonymsByIDRequest()
        {
        }
        
        public getAphiaSynonymsByIDRequest(int AphiaID)
        {
            this.AphiaID = AphiaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaSynonymsByIDResponse", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaSynonymsByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord[] @return;
        
        public getAphiaSynonymsByIDResponse()
        {
        }
        
        public getAphiaSynonymsByIDResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaVernacularsByID", WrapperNamespace="http://aphia/v1.0/AphiaVernaculars", IsWrapped=true)]
    public partial class getAphiaVernacularsByIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        public getAphiaVernacularsByIDRequest()
        {
        }
        
        public getAphiaVernacularsByIDRequest(int AphiaID)
        {
            this.AphiaID = AphiaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaVernacularsByIDResponse", WrapperNamespace="http://aphia/v1.0/AphiaVernaculars", IsWrapped=true)]
    public partial class getAphiaVernacularsByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.Vernacular[] @return;
        
        public getAphiaVernacularsByIDResponse()
        {
        }
        
        public getAphiaVernacularsByIDResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.Vernacular[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaChildrenByID", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaChildrenByIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int offset;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public bool marine_only;
        
        public getAphiaChildrenByIDRequest()
        {
        }
        
        public getAphiaChildrenByIDRequest(int AphiaID, int offset, bool marine_only)
        {
            this.AphiaID = AphiaID;
            this.offset = offset;
            this.marine_only = marine_only;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaChildrenByIDResponse", WrapperNamespace="http://aphia/v1.0/AphiaRecords", IsWrapped=true)]
    public partial class getAphiaChildrenByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord[] @return;
        
        public getAphiaChildrenByIDResponse()
        {
        }
        
        public getAphiaChildrenByIDResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="matchAphiaRecordsByNames", WrapperNamespace="http://aphia/v1.0/AphiaMatches", IsWrapped=true)]
    public partial class matchAphiaRecordsByNamesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] scientificnames;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public bool marine_only;
        
        public matchAphiaRecordsByNamesRequest()
        {
        }
        
        public matchAphiaRecordsByNamesRequest(string[] scientificnames, bool marine_only)
        {
            this.scientificnames = scientificnames;
            this.marine_only = marine_only;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="matchAphiaRecordsByNamesResponse", WrapperNamespace="http://aphia/v1.0/AphiaMatches", IsWrapped=true)]
    public partial class matchAphiaRecordsByNamesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord[][] @return;
        
        public matchAphiaRecordsByNamesResponse()
        {
        }
        
        public matchAphiaRecordsByNamesResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaRecord[][] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaDistributionsByID", WrapperNamespace="http://aphia/v1.0/AphiaDistributions", IsWrapped=true)]
    public partial class getAphiaDistributionsByIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int AphiaID;
        
        public getAphiaDistributionsByIDRequest()
        {
        }
        
        public getAphiaDistributionsByIDRequest(int AphiaID)
        {
            this.AphiaID = AphiaID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaDistributionsByIDResponse", WrapperNamespace="http://aphia/v1.0/AphiaDistributions", IsWrapped=true)]
    public partial class getAphiaDistributionsByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.Distribution[] @return;
        
        public getAphiaDistributionsByIDResponse()
        {
        }
        
        public getAphiaDistributionsByIDResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.Distribution[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaAttributeKeysByID", WrapperNamespace="http://aphia/v1.0/AttributeKeys", IsWrapped=true)]
    public partial class getAphiaAttributeKeysByIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public bool include_children;
        
        public getAphiaAttributeKeysByIDRequest()
        {
        }
        
        public getAphiaAttributeKeysByIDRequest(int id, bool include_children)
        {
            this.id = id;
            this.include_children = include_children;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaAttributeKeysByIDResponse", WrapperNamespace="http://aphia/v1.0/AttributeKeys", IsWrapped=true)]
    public partial class getAphiaAttributeKeysByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AttributeKey[] @return;
        
        public getAphiaAttributeKeysByIDResponse()
        {
        }
        
        public getAphiaAttributeKeysByIDResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AttributeKey[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaAttributeValuesByCategoryID", WrapperNamespace="http://aphia/v1.0/AttributeValues", IsWrapped=true)]
    public partial class getAphiaAttributeValuesByCategoryIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int id;
        
        public getAphiaAttributeValuesByCategoryIDRequest()
        {
        }
        
        public getAphiaAttributeValuesByCategoryIDRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaAttributeValuesByCategoryIDResponse", WrapperNamespace="http://aphia/v1.0/AttributeValues", IsWrapped=true)]
    public partial class getAphiaAttributeValuesByCategoryIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AttributeValue[] @return;
        
        public getAphiaAttributeValuesByCategoryIDResponse()
        {
        }
        
        public getAphiaAttributeValuesByCategoryIDResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AttributeValue[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaIDsByAttributeKeyID", WrapperNamespace="http://aphia/v1.0/aphiaids", IsWrapped=true)]
    public partial class getAphiaIDsByAttributeKeyIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int offset;
        
        public getAphiaIDsByAttributeKeyIDRequest()
        {
        }
        
        public getAphiaIDsByAttributeKeyIDRequest(int id, int offset)
        {
            this.id = id;
            this.offset = offset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaIDsByAttributeKeyIDResponse", WrapperNamespace="http://aphia/v1.0/aphiaids", IsWrapped=true)]
    public partial class getAphiaIDsByAttributeKeyIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int[] @return;
        
        public getAphiaIDsByAttributeKeyIDResponse()
        {
        }
        
        public getAphiaIDsByAttributeKeyIDResponse(int[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaAttributesByAphiaID", WrapperNamespace="http://aphia/v1.0/Attributes", IsWrapped=true)]
    public partial class getAphiaAttributesByAphiaIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public bool include_inherited;
        
        public getAphiaAttributesByAphiaIDRequest()
        {
        }
        
        public getAphiaAttributesByAphiaIDRequest(int id, bool include_inherited)
        {
            this.id = id;
            this.include_inherited = include_inherited;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAphiaAttributesByAphiaIDResponse", WrapperNamespace="http://aphia/v1.0/Attributes", IsWrapped=true)]
    public partial class getAphiaAttributesByAphiaIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ProcessingTools.Clients.ConnectedServices.Bio.Aphia.Attribute[] @return;
        
        public getAphiaAttributesByAphiaIDResponse()
        {
        }
        
        public getAphiaAttributesByAphiaIDResponse(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.Attribute[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface AphiaNameServicePortTypeChannel : ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaNameServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class AphiaNameServicePortTypeClient : System.ServiceModel.ClientBase<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaNameServicePortType>, ProcessingTools.Clients.ConnectedServices.Bio.Aphia.AphiaNameServicePortType
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AphiaNameServicePortTypeClient() : 
                base(AphiaNameServicePortTypeClient.GetDefaultBinding(), AphiaNameServicePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AphiaNameServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AphiaNameServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(AphiaNameServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), AphiaNameServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AphiaNameServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AphiaNameServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AphiaNameServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AphiaNameServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AphiaNameServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaIDResponse> getAphiaIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaIDRequest request)
        {
            return base.Channel.getAphiaIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsResponse> getAphiaRecordsAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsRequest request)
        {
            return base.Channel.getAphiaRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaNameByIDResponse> getAphiaNameByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaNameByIDRequest request)
        {
            return base.Channel.getAphiaNameByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordByIDResponse> getAphiaRecordByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordByIDRequest request)
        {
            return base.Channel.getAphiaRecordByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordByExtIDResponse> getAphiaRecordByExtIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordByExtIDRequest request)
        {
            return base.Channel.getAphiaRecordByExtIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getExtIDbyAphiaIDResponse> getExtIDbyAphiaIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getExtIDbyAphiaIDRequest request)
        {
            return base.Channel.getExtIDbyAphiaIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsByNamesResponse> getAphiaRecordsByNamesAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsByNamesRequest request)
        {
            return base.Channel.getAphiaRecordsByNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsByVernacularResponse> getAphiaRecordsByVernacularAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsByVernacularRequest request)
        {
            return base.Channel.getAphiaRecordsByVernacularAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsByDateResponse> getAphiaRecordsByDateAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaRecordsByDateRequest request)
        {
            return base.Channel.getAphiaRecordsByDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaClassificationByIDResponse> getAphiaClassificationByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaClassificationByIDRequest request)
        {
            return base.Channel.getAphiaClassificationByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getSourcesByAphiaIDResponse> getSourcesByAphiaIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getSourcesByAphiaIDRequest request)
        {
            return base.Channel.getSourcesByAphiaIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaSynonymsByIDResponse> getAphiaSynonymsByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaSynonymsByIDRequest request)
        {
            return base.Channel.getAphiaSynonymsByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaVernacularsByIDResponse> getAphiaVernacularsByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaVernacularsByIDRequest request)
        {
            return base.Channel.getAphiaVernacularsByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaChildrenByIDResponse> getAphiaChildrenByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaChildrenByIDRequest request)
        {
            return base.Channel.getAphiaChildrenByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.matchAphiaRecordsByNamesResponse> matchAphiaRecordsByNamesAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.matchAphiaRecordsByNamesRequest request)
        {
            return base.Channel.matchAphiaRecordsByNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaDistributionsByIDResponse> getAphiaDistributionsByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaDistributionsByIDRequest request)
        {
            return base.Channel.getAphiaDistributionsByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaAttributeKeysByIDResponse> getAphiaAttributeKeysByIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaAttributeKeysByIDRequest request)
        {
            return base.Channel.getAphiaAttributeKeysByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaAttributeValuesByCategoryIDResponse> getAphiaAttributeValuesByCategoryIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaAttributeValuesByCategoryIDRequest request)
        {
            return base.Channel.getAphiaAttributeValuesByCategoryIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaIDsByAttributeKeyIDResponse> getAphiaIDsByAttributeKeyIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaIDsByAttributeKeyIDRequest request)
        {
            return base.Channel.getAphiaIDsByAttributeKeyIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaAttributesByAphiaIDResponse> getAphiaAttributesByAphiaIDAsync(ProcessingTools.Clients.ConnectedServices.Bio.Aphia.getAphiaAttributesByAphiaIDRequest request)
        {
            return base.Channel.getAphiaAttributesByAphiaIDAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AphiaNameServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AphiaNameServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://www.marinespecies.org/aphia.php?p=soap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AphiaNameServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.AphiaNameServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AphiaNameServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.AphiaNameServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            AphiaNameServicePort,
        }
    }
}
