//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseObjectTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseObjectTests.TestResourceStrings", typeof(TestResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;article article-type=&quot;research-article&quot; dtd-version=&quot;3.0&quot; xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;
        ///    &lt;front&gt;
        ///        &lt;journal-meta&gt;
        ///            &lt;journal-id journal-id-type=&quot;publisher-id&quot;&gt;ZooKeys&lt;/journal-id&gt;
        ///            &lt;journal-title-group&gt;
        ///                &lt;journal-title xml:lang=&quot;en&quot;&gt;ZooKeys&lt;/journal-tit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _10154 {
            get {
                return ResourceManager.GetString("_10154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;&lt;bold&gt;Indonesia: Snellius Expedition 1929–1930.&lt;/bold&gt; RMNH.CRUS.D.56378, ca. 260 specimens, Sissie by Misool, beach, 06. Oct. 1929; RMNH.CRUS.D.56379, ca. 140 specimens; RMNH.CRUS.D.56380, ca. 60 specimens, Ambon, 11.-17.09.1930; RMNH.CRUS.D.56381, ca. 145 specime [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String0 {
            get {
                return ResourceManager.GetString("String0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;&lt;bold&gt;Indonesia.&lt;/bold&gt; RMNH.CRUS.D.2604, 1 male, Indonesia, Endeh, Flores Island, leg. H. ten Kate, 1891; Measurements: CL 8,5mm × CW 9,0 mm; RMNH.CRUS.D.1643, 5 males, 2 females (1ov), Indonesia, Endeh, Flores Island, leg. H. ten Kate, 1891; RMNH.CRUS.D.56410, 4  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;Guinea: ZMB 78251 (male), ZMB 78252 (female), Kankan Region (&lt;locality-coordinates latitude=&quot;9.21000&quot; longitude=&quot;8.93000&quot;&gt;9.21; 8.93&lt;/locality-coordinates&gt;), 1119 m a.s.l.; ZMB 78253-58 (5 females), N’Zérékoré Region (&lt;locality-coordinates latitude=&quot;7.98000&quot; longit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;&lt;italic&gt;&lt;tp:taxon-name type=&quot;lower&quot;&gt;&lt;tp:taxon-name-part taxon-name-part-type=&quot;genus&quot;&gt;Odontobatrachus&lt;/tp:taxon-name-part&gt; &lt;tp:taxon-name-part taxon-name-part-type=&quot;species&quot;&gt;ziama&lt;/tp:taxon-name-part&gt;&lt;/tp:taxon-name&gt;&lt;/italic&gt; sp. n. in life: &lt;bold&gt;a&lt;/bold&gt;) female p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;Guinea: MHNG 2731.47 (female), Mamou Region (&lt;locality-coordinates latitude=&quot;10.85000&quot; longitude=&quot;12.52000&quot;&gt;10.85; 12.52&lt;/locality-coordinates&gt;), 664 m a.s.l., 22 July 2010; ZFMK 95466, ZMB 78306 (2 females), Kindia Region (&lt;locality-coordinates latitude=&quot;10.81000&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;Guinea: ZMB 78304-05 (2 juveniles), Kindia Region (&lt;locality-coordinates latitude=&quot;10.83000&quot; longitude=&quot;13.81000&quot;&gt;10.83; 13.81&lt;/locality-coordinates&gt;), 253 m a.s.l.; ZMB 78307 (male), Kindia Region (&lt;locality-coordinates latitude=&quot;10.81000&quot; longitude=&quot;13.34000&quot;&gt;10. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;The male holotype has been assigned to this taxon in the DCA analysis of ratios. The holotype is an adult male with a robust body (Fig. &lt;xref ref-type=&quot;fig&quot; rid=&quot;F7&quot;&gt;7&lt;/xref&gt;): snout-urostyle length of 60.4 mm; head width 21.9 mm; head slightly longer than broad; s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;The male holotype has been assigned to this taxon in both DCA analyses (absolute values and ratios). The holotype is an adult male with a robust body (Fig. &lt;xref ref-type=&quot;fig&quot; rid=&quot;F9&quot;&gt;9&lt;/xref&gt;): snout-urostyle length of 55.6 mm; head width 21.6 mm; head slightly  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;ZMB 78355 (male), Republic of Guinea, Nimba Mts., River Mandey (&lt;locality-coordinates latitude=&quot;7.64786&quot; longitude=&quot;8.42397&quot;&gt;Latitude: 7.64786; Longitude: 8.42397&lt;/locality-coordinates&gt;), 694 m a.s.l., 18 June 2009, coll. L. Sandberger-Loua and J. Doumbia.&lt;/p&gt;&lt;/art [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;Guinea: MHNG 2731.49 (male), ZMB 78356 (female), N’Zérékoré Region (&lt;locality-coordinates latitude=&quot;7.65000&quot; longitude=&quot;8.42000&quot;&gt;7.65; 8.42&lt;/locality-coordinates&gt;), 670 m a.s.l., 18 June 2009; MHNG 2731.50, ZMB 78357 (2 females), N’Zérékoré Region (&lt;locality-coordi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;Côte d’Ivoire: ZMB 78326, ZMB 78329 (3 females), ZMB 78327-8 (2 males), Dix-Huit Montagnes Region (&lt;locality-coordinates latitude=&quot;7.85000&quot; longitude=&quot;7.39000&quot;&gt;7.85; 7.39&lt;/locality-coordinates&gt;), app. 500 m a.s.l. Liberia: ZMB 78332 (male), Nimba County (&lt;locality- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;The male holotype has been assigned to this taxon in both DCA analyses (absolute values and ratios). The holotype is an adult male with a slightly robust body (Fig. &lt;xref ref-type=&quot;fig&quot; rid=&quot;F11&quot;&gt;11&lt;/xref&gt;): snout-urostyle length of 48.8 mm; head width 17.1 mm; hea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;&lt;bold&gt;Indonesia.&lt;/bold&gt; RMNH.CRUS.D.56374, holotype, male, CL 8.9 mm × CW 8.7 mm, NW Guinea, Pulau Japen, coast near Sarawandori, leg. W. van Seroei, 24.2.1955. Paratypes: RMNH.CRUS.D.56408, 4 males, 5 females (3 ov), same data as holotype. RMNH.CRUS.D.56375, 2 mal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;Three calls of &lt;italic&gt;&lt;tp:taxon-name type=&quot;lower&quot;&gt;&lt;tp:taxon-name-part taxon-name-part-type=&quot;genus&quot;&gt;Odontobatrachus&lt;/tp:taxon-name-part&gt; &lt;tp:taxon-name-part taxon-name-part-type=&quot;species&quot;&gt;arndti&lt;/tp:taxon-name-part&gt;&lt;/tp:taxon-name&gt;&lt;/italic&gt; were recorded from speci [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;DNA was extracted from legs and occasionally abdomens (for specimens without legs or with deficient amplification) following standard protocols of the commercially available DNeasy Blood &amp;amp; Tissue Kit (QIAgen®). The COI barcode region was amplified using the for [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material (the studied material was partly published by Komnenov 2002, 2003, 2006 and Logunov 2015). MACEDONIA: 1 ♂ (PCMK) Šar Planina [=Shar] Mt., 1320 m a.s.l., 41°48.455&apos;N, 20°47.862&apos;E, pitfall traps, 19 July 1998 (M. Komnenov); 3 ♀ (PCMK) Pelister [=Baba] Mt., 1200-1500 m a.s.l., 41°01.760&apos;N, 21°13.369&apos;E, July 2001 (M. Komnenov); 2 ♂ 1 ♀ (PCMK) Demir Kapija, 550 m a.s.l., 41°20.843&apos;N, 22°18.334&apos;E, 21 May 2005 (M. Komnenov); 1 ♂ (PCMK) Jakupica Mt., 2000 m a.s.l, 41°40.670&apos;N, 21°24.245&apos;E, 11 July 1999 (M. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;&lt;bold&gt; Holotype&lt;/bold&gt;: ♂ (ISEA 000.287) TURKEY, Antalya Province, 18 km SSE of Elmali, Bey Mt. Range, 6 km WSW of Kızlarsivrisi Mt., 1800–2000 m a.s.l., 36°35&apos;N, 30°03&apos;E, 25 April 2009, coll. R.Yu. Dudko, I.I. Lyubechanskij, A.A. Stekolnikov. &lt;bold&gt;Paratypes&lt;/bold [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt; Allotype of &lt;italic&gt;Aelurillus steliosi&lt;/italic&gt;: 1 ♀ (MNHN #AR 13335) “GREECE, Crete, Psiloreitis, Kouroutes (Prefectura Irakleio), near Agios Titos church, 1180 m a.s.l., c. 35°20&apos;N, 25°08&apos;E, 12 June 2001, coll. S. Simaiakis”. Holotype of &lt;italic&gt;Aelurillus cret [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt; &lt;bold&gt;Holotype&lt;/bold&gt;: ♂ (IZSB) BULGARIA, Blagoevgrad Province, Strouma Valley, 2 km S of Kamenitsa, 170-240 m a.s.l., c. 41°38&apos;N, 23°09&apos;E, soil traps, 28 September – 2 February 2002, coll. M. Langourov &amp;amp; S. P. Lazarov. &lt;bold&gt;Paratypes&lt;/bold&gt;: MACEDONIA: 1 ♂ ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt; Holotype of &lt;italic&gt;Aelurillus steliosi&lt;/italic&gt;: ♂ (MNHN #AR 13334) “GREECE, Crete, Skalani (Pref. Irakleio), 230 m a.s.l., c. 35°17&apos;N, 25°11&apos;E, 21 May 2001, coll. S. &lt;!--PageBreak--&gt;Simaiakis”. Holotype of &lt;italic&gt;Asianellus leipoldae&lt;/italic&gt; ♂ (SMNK, 2177) “GR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;Sierra Leone: BMNH 1961.1248-54 (5 juveniles), Western Area; BMNH 1963.1047 (female), Southern Province; BMNH 1964.178 (female), Western Area; ZMB 78196 (juvenile), Western Area Peninsula Forest (&lt;locality-coordinates latitude=&quot;8.35000&quot; longitude=&quot;13.18000&quot;&gt;Latitud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;&lt;xref ref-type=&quot;bibr&quot; rid=&quot;B14&quot;&gt;Boulenger’s (1905)&lt;/xref&gt; species description is based on a series of five specimens in the BMNH collection (1947.2.30.65-69, formerly: 1905.1.27.4-5 and 1905.2.2.15-17). The type series collected by Major F. Smith Royal Army Medical [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;article xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;p&gt;During his service in western Africa, Captain (Local Major) F. Smith researched tropical diseases, prepared species lists of pests and elaborated respective preventive measures (&lt;xref ref-type=&quot;bibr&quot; rid=&quot;B65&quot;&gt;Smith 1902&lt;/xref&gt;, &lt;xref ref-type=&quot;bibr&quot; rid=&quot;B66&quot;&gt;1905 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;article article-type=&quot;research-article&quot; dtd-version=&quot;3.0&quot; xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;
        ///    &lt;front&gt;
        ///        &lt;journal-meta&gt;
        ///            &lt;journal-id journal-id-type=&quot;publisher-id&quot;&gt;ZooKeys&lt;/journal-id&gt;
        ///            &lt;journal-title-group&gt;
        ///                &lt;journal-title xml:lang=&quot;en&quot;&gt;ZooKeys&lt;/journal-tit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZK10154 {
            get {
                return ResourceManager.GetString("ZK10154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;article article-type=&quot;research-article&quot; dtd-version=&quot;3.0&quot; xml:lang=&quot;en&quot; xmlns:tp=&quot;http://www.plazi.org/taxpub&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:mml=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;
        ///    &lt;front&gt;
        ///        &lt;journal-meta&gt;
        ///            &lt;journal-id journal-id-type=&quot;publisher-id&quot;&gt;ZooKeys&lt;/journal-id&gt;
        ///            &lt;journal-title-group&gt;
        ///                &lt;journal-title xml:lang=&quot;en&quot;&gt;ZooKeys&lt;/journal-tit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ZK8817 {
            get {
                return ResourceManager.GetString("ZK8817", resourceCulture);
            }
        }
    }
}
