//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Bio.Taxonomy.ItisDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class hierarchy
    {
        public string hierarchy_string { get; set; }
        public int TSN { get; set; }
        public Nullable<int> Parent_TSN { get; set; }
        public int level { get; set; }
        public int ChildrenCount { get; set; }
    }
}
