//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Bio.Taxonomy.ItisDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class kingdom
    {
        public int kingdom_id { get; set; }
        public string kingdom_name { get; set; }
        public System.DateTime update_date { get; set; }
    }
}
