//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Bio.Taxonomy.ItisDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class synonym_names
    {
        public int tsn { get; set; }
        public string completename { get; set; }
        public int tsn_accepted { get; set; }
        public string acceptedname { get; set; }
    }
}
