//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Documents.Services.Data.Tests
{
    using System;
    using System.Linq;
    using System.Xml;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    public partial class XmlPresenterTests
    {
        #region GetHtmlTests

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_GetHtml_WithNullUserId_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.GetHtml(null, this.articleId, this.documentId).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_GetHtml_WithNullUserId_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.GetHtml(null, this.articleId, this.documentId).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    UserIdParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(UserIdParamName));
            }
        }

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_GetHtml_WithNullArticleId_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.GetHtml(this.userId, null, this.documentId).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_GetHtml_WithNullArticleId_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.GetHtml(this.userId, null, this.documentId).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    ArticleIdParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(ArticleIdParamName));
            }
        }

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_GetHtml_WithNullDocumentId_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.GetHtml(this.userId, this.articleId, null).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_GetHtml_WithNullDocumentId_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.GetHtml(this.userId, this.articleId, null).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    DocumentIdParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(DocumentIdParamName));
            }
        }

        #endregion  GetHtmlTests

        #region GetXmlTests

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_GetXml_WithNullUserId_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.GetXml(null, this.articleId, this.documentId).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_GetXml_WithNullUserId_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.GetXml(null, this.articleId, this.documentId).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    UserIdParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(UserIdParamName));
            }
        }

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_GetXml_WithNullArticleId_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.GetXml(this.userId, null, this.documentId).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_GetXml_WithNullArticleId_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.GetXml(this.userId, null, this.documentId).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    ArticleIdParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(ArticleIdParamName));
            }
        }

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_GetXml_WithNullDocumentId_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.GetXml(this.userId, this.articleId, null).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_GetXml_WithNullDocumentId_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.GetXml(this.userId, this.articleId, null).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    DocumentIdParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(DocumentIdParamName));
            }
        }

        #endregion  GetXmlTests

        

        #region SaveHtmlTests

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_SaveHtml_WithNullUserId_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.SaveHtml(null, this.articleId, this.document, ValidContent).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_SaveHtml_WithNullUserId_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.SaveHtml(null, this.articleId, this.document, ValidContent).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    UserIdParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(UserIdParamName));
            }
        }

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_SaveHtml_WithNullArticleId_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.SaveHtml(this.userId, null, this.document, ValidContent).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_SaveHtml_WithNullArticleId_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.SaveHtml(this.userId, null, this.document, ValidContent).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    ArticleIdParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(ArticleIdParamName));
            }
        }

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_SaveHtml_WithNullDocument_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.SaveHtml(this.userId, this.articleId, null, ValidContent).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_SaveHtml_WithNullDocument_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.SaveHtml(this.userId, this.articleId, null, ValidContent).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    DocumentParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(DocumentParamName));
            }
        }

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_SaveHtml_WithNullContent_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.SaveHtml(this.userId, this.articleId, this.document, null).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_SaveHtml_WithNullContent_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.SaveHtml(this.userId, this.articleId, this.document, null).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    ContentParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(ContentParamName));
            }
        }

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_SaveHtml_WithEmptyContent_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.SaveHtml(this.userId, this.articleId, this.document, string.Empty).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_SaveHtml_WithEmptyContent_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.SaveHtml(this.userId, this.articleId, this.document, string.Empty).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    ContentParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(ContentParamName));
            }
        }

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_SaveHtml_WithWhitespaceContent_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.SaveHtml(this.userId, this.articleId, this.document, @"  
            ").Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_SaveHtml_WithWhitespaceContent_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.SaveHtml(this.userId, this.articleId, this.document, @"  
                ").Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    ContentParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(ContentParamName));
            }
        }


        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_SaveHtml_WithInvalidXmlContent_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.SaveHtml(this.userId, this.articleId, this.document, InvalidContent).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_SaveHtml_WithInvalidXmlContent_ShouldThrowAggregateExceptionWithXmlException()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.SaveHtml(this.userId, this.articleId, this.document, InvalidContent).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is XmlException),
                    NumberOfInnerExceptionsShouldBeMessage);
            }
        }

        #endregion  SaveHtmlTests

        #region SaveXmlTests

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_SaveXml_WithNullUserId_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.SaveXml(null, this.articleId, this.document, ValidContent).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_SaveXml_WithNullUserId_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.SaveXml(null, this.articleId, this.document, ValidContent).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    UserIdParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(UserIdParamName));
            }
        }

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_SaveXml_WithNullArticleId_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.SaveXml(this.userId, null, this.document, ValidContent).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_SaveXml_WithNullArticleId_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.SaveXml(this.userId, null, this.document, ValidContent).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    ArticleIdParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(ArticleIdParamName));
            }
        }

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_SaveXml_WithNullDocument_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.SaveXml(this.userId, this.articleId, null, ValidContent).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_SaveXml_WithNullDocument_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.SaveXml(this.userId, this.articleId, null, ValidContent).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    DocumentParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(DocumentParamName));
            }
        }

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_SaveXml_WithNullContent_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.SaveXml(this.userId, this.articleId, this.document, null).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_SaveXml_WithNullContent_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.SaveXml(this.userId, this.articleId, this.document, null).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    ContentParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(ContentParamName));
            }
        }

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_SaveXml_WithEmptyContent_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.SaveXml(this.userId, this.articleId, this.document, string.Empty).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_SaveXml_WithEmptyContent_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.SaveXml(this.userId, this.articleId, this.document, string.Empty).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    ContentParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(ContentParamName));
            }
        }

        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_SaveXml_WithWhitespaceContent_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.SaveXml(this.userId, this.articleId, this.document, @"  
            ").Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_SaveXml_WithWhitespaceContent_ShouldThrowAggregateExceptionWithArgumentNullExceptionWithCorrectParamName()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.SaveXml(this.userId, this.articleId, this.document, @"  
                ").Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is ArgumentNullException),
                    NumberOfInnerExceptionsShouldBeMessage);

                var argumentNullException = e.InnerExceptions.First(ex => ex is ArgumentNullException) as ArgumentNullException;

                Assert.AreEqual(
                    ContentParamName,
                    argumentNullException.ParamName,
                    this.GetParamNameShouldBeMessage(ContentParamName));
            }
        }


        [TestMethod]
        [Timeout(1000)]
        [ExpectedException(typeof(AggregateException), AllowDerivedTypes = false)]
        public void XmlPresenter_SaveXml_WithInvalidXmlContent_ShouldThrowAggregateException()
        {
            var presenter = new XmlPresenter(this.service);
            var result = presenter.SaveXml(this.userId, this.articleId, this.document, InvalidContent).Result;
        }

        [TestMethod]
        [Timeout(1000)]
        public void XmlPresenter_SaveXml_WithInvalidXmlContent_ShouldThrowAggregateExceptionWithXmlException()
        {
            var presenter = new XmlPresenter(this.service);
            try
            {
                var result = presenter.SaveXml(this.userId, this.articleId, this.document, InvalidContent).Result;
            }
            catch (AggregateException e)
            {
                Assert.AreEqual(
                    NumberOfInnerArgumentNullExceptions,
                    e.InnerExceptions.Count(ex => ex is XmlException),
                    NumberOfInnerExceptionsShouldBeMessage);
            }
        }

        #endregion  SaveXmlTests

            }
}

