//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessingTools.Common.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article will not be deleted because it contains documents..
        /// </summary>
        public static string ArticleWillNotBeDeletedBecauseItContainsDocuments {
            get {
                return ResourceManager.GetString("ArticleWillNotBeDeletedBecauseItContainsDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document content is not acknowledged..
        /// </summary>
        public static string DeleteDocumentContentIsNotAcknowledged {
            get {
                return ResourceManager.GetString("DeleteDocumentContentIsNotAcknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document is not acknowledged..
        /// </summary>
        public static string DeleteDocumentIsNotAcknowledged {
            get {
                return ResourceManager.GetString("DeleteDocumentIsNotAcknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal will not be deleted because it contains related articles..
        /// </summary>
        public static string JournalWillNotBeDeletedBecauseItContainsRelatedArticles {
            get {
                return ResourceManager.GetString("JournalWillNotBeDeletedBecauseItContainsRelatedArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher will not be deleted because it contains related journals..
        /// </summary>
        public static string PublisherWillNotBeDeletedBecauseItContainsRelatedJournals {
            get {
                return ResourceManager.GetString("PublisherWillNotBeDeletedBecauseItContainsRelatedJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified article does not have any final documents..
        /// </summary>
        public static string SpecifiedArticleDoesNotHaveAnyFinalDocuments {
            get {
                return ResourceManager.GetString("SpecifiedArticleDoesNotHaveAnyFinalDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified article does not have valid Journal ID..
        /// </summary>
        public static string SpecifiedArticleDoesNotHaveValidJournalId {
            get {
                return ResourceManager.GetString("SpecifiedArticleDoesNotHaveValidJournalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified journal is null..
        /// </summary>
        public static string SpecifiedJournalIsNull {
            get {
                return ResourceManager.GetString("SpecifiedJournalIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified publisher is null..
        /// </summary>
        public static string SpecifiedPublisherIsNull {
            get {
                return ResourceManager.GetString("SpecifiedPublisherIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all documents as not final failed..
        /// </summary>
        public static string UpdateAllDocumentsAsNotFinalFailed {
            get {
                return ResourceManager.GetString("UpdateAllDocumentsAsNotFinalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update single document as final failed..
        /// </summary>
        public static string UpdateSingleDocumentAsFinalFailed {
            get {
                return ResourceManager.GetString("UpdateSingleDocumentAsFinalFailed", resourceCulture);
            }
        }
    }
}
