//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Itis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class expert
    {
        public string expert_id_prefix { get; set; }
        public int expert_id { get; set; }
        public string expert1 { get; set; }
        public string exp_comment { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
