//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Itis.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ItisEntities : DbContext
    {
        public ItisEntities()
            : base("name=ItisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<expert> experts { get; set; }
        public virtual DbSet<geographic_div> geographic_div { get; set; }
        public virtual DbSet<hierarchy> hierarchies { get; set; }
        public virtual DbSet<jurisdiction> jurisdictions { get; set; }
        public virtual DbSet<kingdom> kingdoms { get; set; }
        public virtual DbSet<longname> longnames { get; set; }
        public virtual DbSet<other_sources> other_sources { get; set; }
        public virtual DbSet<publication> publications { get; set; }
        public virtual DbSet<reference_links> reference_links { get; set; }
        public virtual DbSet<strippedauthor> strippedauthors { get; set; }
        public virtual DbSet<synonym_links> synonym_links { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<taxon_authors_lkp> taxon_authors_lkp { get; set; }
        public virtual DbSet<taxon_unit_types> taxon_unit_types { get; set; }
        public virtual DbSet<taxonomic_units> taxonomic_units { get; set; }
        public virtual DbSet<tu_comments_links> tu_comments_links { get; set; }
        public virtual DbSet<vern_ref_links> vern_ref_links { get; set; }
        public virtual DbSet<vernacular> vernaculars { get; set; }
        public virtual DbSet<synonym_names> synonym_names { get; set; }
    }
}
