//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Itis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class longname
    {
        public int tsn { get; set; }
        public string completename { get; set; }
    }
}
