//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Itis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class other_sources
    {
        public string source_id_prefix { get; set; }
        public int source_id { get; set; }
        public string source_type { get; set; }
        public string source { get; set; }
        public string version { get; set; }
        public Nullable<System.DateTime> acquisition_date { get; set; }
        public string source_comment { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
