//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessingTools.Itis.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class strippedauthor
    {
        public int taxon_author_id { get; set; }
        public string shortauthor { get; set; }
    }
}
